### ISSUE TITLE
ipinfo.io limit

### ISSUE THREAD

**Issue by cognoscibilis** [brainfucksec/kalitorify#23]
**Describe the bug**
Program stops at "Checking your public IP" step

**Program error message**
error:
title:Ratelimitexceeded,
message:Upgradetoincreaseyourusagelimitsathttps://ipinfo.io/pricing,orcontactusviahttps://ipinfo.io/contact

or 

[ failed ] curl: HTTP request error

**Comment by brainfucksec** [comment]
Hi @cognoscibilis, thanks for this report.
The message is due to the fact that too many requests were made with the IP of that Tor Exit Node to one of the two sites that the program uses:

http://ipinfo.io
https://ipapi.co/json

Change Tor circuit (public IP) with the `--restart ` command then repeat the request with the `--ipinfo` command.

**Comment by brainfucksec** [comment]
Since it’s been one month, I hope things are working well for you
now. I’ll close the issue until we can confirm it’s still happening. I’m
happy to continue further discussion whenever needed.
