### ISSUE TITLE
With VPN??

### ISSUE THREAD

**Issue by dclaymd** [brainfucksec/kalitorify#26]
I'm trying to use your torify program (great program btw) along with NordVPN........any suggestions? If i start the torify program first the VPN doen't connect and vice versa. Let me know what more information I need to provide to come to a solution.

**Comment by brainfucksec** [comment]
Hi @dclaymd, you can't configure the connection simply because you can't use transparent proxy through tor and then connect to a vpn server, anyway you have several alternatives, but this is a long speech which is not the case in this section, I suggest you start from these sources to learn about the advantages and disadvantages of each configuration:

- https://security.stackexchange.com/questions/72679/differences-between-using-tor-browser-and-vpn?rq=1
- https://www.expressvpn.com/how-to-use-vpn/tor-vpn

Remember though that adding other proxies in a connection does not always mean security and anonymity, there are several factors to evaluate, however as explained in the [security section of kalitorify README](https://github.com/brainfucksec/kalitorify#security) the most secure method for anonymous surfing with Tor Network is the [Isolating Proxy](https://trac.torproject.org/projects/tor/wiki/doc/TorifyHOWTO/IsolatingProxy)

I'm glad you enjoyed the program, hello and good work :)
