### ISSUE TITLE
Temporary failure in name resolution after -c option

### ISSUE THREAD

**Issue by windom3arle** [brainfucksec/kalitorify#38]
I'm experiencing a dns issue when I try to stop kalitorify using the -c option: after that I cannot ping anything even If I restart the network card, always have a "Temporary failure in name resolution" .
To solve that I must restart the machine (kali on vbox).
Is anyone experiencing the same issue?

**Comment by brainfucksec** [comment]
Hi @windom3arle, thanks for the report.
This is a problem that often occurred in previous versions of `kalitorify`, but from the results of my tests I should have solved with the latest versions.

Please check if you have the latest version: 

https://github.com/brainfucksec/kalitorify/releases

Otherwise it may depend on your particular network configuration, however I will run other tests to verify.

**Comment by windom3arle** [comment]
Thank You so much for yr.reply.
I can confirm you it's the latest version given that I installed that the very same day I opened the issue...
Anyway some days ago I've installed the "kali anonsurf" script too to give it a try and (dont' ask me why) the issue automagically solved: now I'm able to start/stop both (kali anonsurf or kalitorify) without experiencing any issues when i try to get back to clearnet.
really don't know why...

**Comment by brainfucksec** [comment]
Generally a **"Name Resolution" error** is due to the DNS settings on `/etc/resolv.conf` file, but I realized that in older versions, `kalitorify` when starting it did not immediately change the` iptables`, therefore it interfered with the settings of the file mentioned above. So, if the program was terminated, the `/etc/resolv.conf` file remained with the settings for the Tor proxy (with the value 127.0.0.1) and the system, returned to "clearnet" could not resolve the names because he did not have the DNS set.
Probably a similar problem has occurred and by starting one of the two scripts (kali-anonsurf / kalitorify) you have reset the network settings to default values and now everything works correctly (these two scripts are similar).

Anyway, I'm glad you solved the problem and thank you for the information.

**Comment by brainfucksec** [comment]
Related to ISSUE #41 
FIXED
